### PR TITLE
Update ru.js for sky dist event

### PR DESCRIPTION
**Pull request by gogo-tattoo**
Russian localization for Skycoin dist page.

### CODE REVIEW

**Comment by angusfretwell** [comment]
@gogo-tattoo Thanks! Could you do a `yarn build` and commit the output?

**Comment by gogo-tattoo** [comment]
No formatting errors for me:

$ yarn build
yarn build v0.27.5
$ react-scripts build
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  141.46 KB (+287 B)  build/static/js/main.720ddd9a.js
  1.19 KB             build/static/css/main.821595f3.css

The project was built assuming it is hosted at the server root.
To override this, specify the homepage in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build

Done in 14.03s.

**Comment by gogo-tattoo** [comment]
Do you know if anybody is doing the Chinese version right now? We can prepare it shortly, otherwise.

**Comment by angusfretwell** [comment]
@gogo-tattoo Cool, the build directory should change after you run it, can you please commit that 😄

**Comment by gogo-tattoo** [comment]
Ok, let me try...

**Pull request closed without merging**
